### PR TITLE
Emit url matches to callback

### PR DESCRIPTION
**Pull request by aekeus**
- Emit matches to a callback from ad-info
- Updated bable versions
- Bumped NPM version

### CODE REVIEW

**Comment by aekeus** [comment]
The ABPFilterParser returns true / false without extra information concerning what was matched. If we also return the matches with the true / false value then the callback would not be necessary in ABP. Please let me know which you prefer (or if you have a better idea). Thanks.

**Comment by bbondy** [comment]
Can `cachedInputData.matchedFilters` be used?

**Comment by aekeus** [comment]
Ok, that makes sense. I will look into using the entries in cachedInputData.matchedFilters to feed the queue.

**Comment by aekeus** [comment]
No changes required if we use cachedInputData.matchedFilters

**Pull request closed without merging**
